/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  colors: {
    primary: {
      50: {
        key: "{colors.primary.50}",
        value: "#ECFEFC",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#ECFEFC",
          key: "{colors.primary.50}",
        },
        name: "ColorsPrimary50",
        attributes: {
          category: "colors",
          type: "primary",
          item: "50",
        },
        path: ["colors", "primary", "50"],
      },
      100: {
        key: "{colors.primary.100}",
        value: "#DDFDF9",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#DDFDF9",
          key: "{colors.primary.100}",
        },
        name: "ColorsPrimary100",
        attributes: {
          category: "colors",
          type: "primary",
          item: "100",
        },
        path: ["colors", "primary", "100"],
      },
      200: {
        key: "{colors.primary.200}",
        value: "#B7FAF3",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#B7FAF3",
          key: "{colors.primary.200}",
        },
        name: "ColorsPrimary200",
        attributes: {
          category: "colors",
          type: "primary",
          item: "200",
        },
        path: ["colors", "primary", "200"],
      },
      300: {
        key: "{colors.primary.300}",
        value: "#95F8ED",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#95F8ED",
          key: "{colors.primary.300}",
        },
        name: "ColorsPrimary300",
        attributes: {
          category: "colors",
          type: "primary",
          item: "300",
        },
        path: ["colors", "primary", "300"],
      },
      400: {
        key: "{colors.primary.400}",
        value: "#74F6E7",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#74F6E7",
          key: "{colors.primary.400}",
        },
        name: "ColorsPrimary400",
        attributes: {
          category: "colors",
          type: "primary",
          item: "400",
        },
        path: ["colors", "primary", "400"],
      },
      500: {
        key: "{colors.primary.500}",
        value: "#51F4E1",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#51F4E1",
          key: "{colors.primary.500}",
        },
        name: "ColorsPrimary500",
        attributes: {
          category: "colors",
          type: "primary",
          item: "500",
        },
        path: ["colors", "primary", "500"],
      },
      600: {
        key: "{colors.primary.600}",
        value: "#14F0D6",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#14F0D6",
          key: "{colors.primary.600}",
        },
        name: "ColorsPrimary600",
        attributes: {
          category: "colors",
          type: "primary",
          item: "600",
        },
        path: ["colors", "primary", "600"],
      },
      700: {
        key: "{colors.primary.700}",
        value: "#0CB6A2",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#0CB6A2",
          key: "{colors.primary.700}",
        },
        name: "ColorsPrimary700",
        attributes: {
          category: "colors",
          type: "primary",
          item: "700",
        },
        path: ["colors", "primary", "700"],
      },
      800: {
        key: "{colors.primary.800}",
        value: "#08786B",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#08786B",
          key: "{colors.primary.800}",
        },
        name: "ColorsPrimary800",
        attributes: {
          category: "colors",
          type: "primary",
          item: "800",
        },
        path: ["colors", "primary", "800"],
      },
      900: {
        key: "{colors.primary.900}",
        value: "#043E38",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#043E38",
          key: "{colors.primary.900}",
        },
        name: "ColorsPrimary900",
        attributes: {
          category: "colors",
          type: "primary",
          item: "900",
        },
        path: ["colors", "primary", "900"],
      },
      950: {
        key: "{colors.primary.950}",
        value: "#021D1A",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#021D1A",
          key: "{colors.primary.950}",
        },
        name: "ColorsPrimary950",
        attributes: {
          category: "colors",
          type: "primary",
          item: "950",
        },
        path: ["colors", "primary", "950"],
      },
    },
    neutral: {
      50: {
        key: "{colors.neutral.50}",
        value: "#ECEEFE",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#ECEEFE",
          key: "{colors.neutral.50}",
        },
        name: "ColorsNeutral50",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "50",
        },
        path: ["colors", "neutral", "50"],
      },
      100: {
        key: "{colors.neutral.100}",
        value: "#DDE1FD",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#DDE1FD",
          key: "{colors.neutral.100}",
        },
        name: "ColorsNeutral100",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "100",
        },
        path: ["colors", "neutral", "100"],
      },
      200: {
        key: "{colors.neutral.200}",
        value: "#B7BFFA",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#B7BFFA",
          key: "{colors.neutral.200}",
        },
        name: "ColorsNeutral200",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "200",
        },
        path: ["colors", "neutral", "200"],
      },
      300: {
        key: "{colors.neutral.300}",
        value: "#95A1F8",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#95A1F8",
          key: "{colors.neutral.300}",
        },
        name: "ColorsNeutral300",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "300",
        },
        path: ["colors", "neutral", "300"],
      },
      400: {
        key: "{colors.neutral.400}",
        value: "#7483F6",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#7483F6",
          key: "{colors.neutral.400}",
        },
        name: "ColorsNeutral400",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "400",
        },
        path: ["colors", "neutral", "400"],
      },
      500: {
        key: "{colors.neutral.500}",
        value: "#5164F4",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#5164F4",
          key: "{colors.neutral.500}",
        },
        name: "ColorsNeutral500",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "500",
        },
        path: ["colors", "neutral", "500"],
      },
      600: {
        key: "{colors.neutral.600}",
        value: "#142EF0",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#142EF0",
          key: "{colors.neutral.600}",
        },
        name: "ColorsNeutral600",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "600",
        },
        path: ["colors", "neutral", "600"],
      },
      700: {
        key: "{colors.neutral.700}",
        value: "#0C1FB6",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#0C1FB6",
          key: "{colors.neutral.700}",
        },
        name: "ColorsNeutral700",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "700",
        },
        path: ["colors", "neutral", "700"],
      },
      800: {
        key: "{colors.neutral.800}",
        value: "#081578",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#081578",
          key: "{colors.neutral.800}",
        },
        name: "ColorsNeutral800",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "800",
        },
        path: ["colors", "neutral", "800"],
      },
      900: {
        key: "{colors.neutral.900}",
        value: "#040B3E",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#040B3E",
          key: "{colors.neutral.900}",
        },
        name: "ColorsNeutral900",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "900",
        },
        path: ["colors", "neutral", "900"],
      },
      950: {
        key: "{colors.neutral.950}",
        value: "#02051D",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#02051D",
          key: "{colors.neutral.950}",
        },
        name: "ColorsNeutral950",
        attributes: {
          category: "colors",
          type: "neutral",
          item: "950",
        },
        path: ["colors", "neutral", "950"],
      },
    },
    warning: {
      50: {
        key: "{colors.warning.50}",
        value: "#FEFAEC",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FEFAEC",
          key: "{colors.warning.50}",
        },
        name: "ColorsWarning50",
        attributes: {
          category: "colors",
          type: "warning",
          item: "50",
        },
        path: ["colors", "warning", "50"],
      },
      100: {
        key: "{colors.warning.100}",
        value: "#FCF5D4",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FCF5D4",
          key: "{colors.warning.100}",
        },
        name: "ColorsWarning100",
        attributes: {
          category: "colors",
          type: "warning",
          item: "100",
        },
        path: ["colors", "warning", "100"],
      },
      200: {
        key: "{colors.warning.200}",
        value: "#FAECAD",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FAECAD",
          key: "{colors.warning.200}",
        },
        name: "ColorsWarning200",
        attributes: {
          category: "colors",
          type: "warning",
          item: "200",
        },
        path: ["colors", "warning", "200"],
      },
      300: {
        key: "{colors.warning.300}",
        value: "#F7E282",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#F7E282",
          key: "{colors.warning.300}",
        },
        name: "ColorsWarning300",
        attributes: {
          category: "colors",
          type: "warning",
          item: "300",
        },
        path: ["colors", "warning", "300"],
      },
      400: {
        key: "{colors.warning.400}",
        value: "#F5D95C",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#F5D95C",
          key: "{colors.warning.400}",
        },
        name: "ColorsWarning400",
        attributes: {
          category: "colors",
          type: "warning",
          item: "400",
        },
        path: ["colors", "warning", "400"],
      },
      500: {
        key: "{colors.warning.500}",
        value: "#F2CE30",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#F2CE30",
          key: "{colors.warning.500}",
        },
        name: "ColorsWarning500",
        attributes: {
          category: "colors",
          type: "warning",
          item: "500",
        },
        path: ["colors", "warning", "500"],
      },
      600: {
        key: "{colors.warning.600}",
        value: "#DDB70E",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#DDB70E",
          key: "{colors.warning.600}",
        },
        name: "ColorsWarning600",
        attributes: {
          category: "colors",
          type: "warning",
          item: "600",
        },
        path: ["colors", "warning", "600"],
      },
      700: {
        key: "{colors.warning.700}",
        value: "#A3870A",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#A3870A",
          key: "{colors.warning.700}",
        },
        name: "ColorsWarning700",
        attributes: {
          category: "colors",
          type: "warning",
          item: "700",
        },
        path: ["colors", "warning", "700"],
      },
      800: {
        key: "{colors.warning.800}",
        value: "#6E5B07",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#6E5B07",
          key: "{colors.warning.800}",
        },
        name: "ColorsWarning800",
        attributes: {
          category: "colors",
          type: "warning",
          item: "800",
        },
        path: ["colors", "warning", "800"],
      },
      900: {
        key: "{colors.warning.900}",
        value: "#352C03",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#352C03",
          key: "{colors.warning.900}",
        },
        name: "ColorsWarning900",
        attributes: {
          category: "colors",
          type: "warning",
          item: "900",
        },
        path: ["colors", "warning", "900"],
      },
      950: {
        key: "{colors.warning.950}",
        value: "#1D1802",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#1D1802",
          key: "{colors.warning.950}",
        },
        name: "ColorsWarning950",
        attributes: {
          category: "colors",
          type: "warning",
          item: "950",
        },
        path: ["colors", "warning", "950"],
      },
    },
    danger: {
      50: {
        key: "{colors.danger.50}",
        value: "#FFEBF0",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FFEBF0",
          key: "{colors.danger.50}",
        },
        name: "ColorsDanger50",
        attributes: {
          category: "colors",
          type: "danger",
          item: "50",
        },
        path: ["colors", "danger", "50"],
      },
      100: {
        key: "{colors.danger.100}",
        value: "#FFD6E1",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FFD6E1",
          key: "{colors.danger.100}",
        },
        name: "ColorsDanger100",
        attributes: {
          category: "colors",
          type: "danger",
          item: "100",
        },
        path: ["colors", "danger", "100"],
      },
      200: {
        key: "{colors.danger.200}",
        value: "#FFB3C6",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FFB3C6",
          key: "{colors.danger.200}",
        },
        name: "ColorsDanger200",
        attributes: {
          category: "colors",
          type: "danger",
          item: "200",
        },
        path: ["colors", "danger", "200"],
      },
      300: {
        key: "{colors.danger.300}",
        value: "#FE8AA7",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FE8AA7",
          key: "{colors.danger.300}",
        },
        name: "ColorsDanger300",
        attributes: {
          category: "colors",
          type: "danger",
          item: "300",
        },
        path: ["colors", "danger", "300"],
      },
      400: {
        key: "{colors.danger.400}",
        value: "#FE678D",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FE678D",
          key: "{colors.danger.400}",
        },
        name: "ColorsDanger400",
        attributes: {
          category: "colors",
          type: "danger",
          item: "400",
        },
        path: ["colors", "danger", "400"],
      },
      500: {
        key: "{colors.danger.500}",
        value: "#FE406F",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FE406F",
          key: "{colors.danger.500}",
        },
        name: "ColorsDanger500",
        attributes: {
          category: "colors",
          type: "danger",
          item: "500",
        },
        path: ["colors", "danger", "500"],
      },
      600: {
        key: "{colors.danger.600}",
        value: "#FE0140",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#FE0140",
          key: "{colors.danger.600}",
        },
        name: "ColorsDanger600",
        attributes: {
          category: "colors",
          type: "danger",
          item: "600",
        },
        path: ["colors", "danger", "600"],
      },
      700: {
        key: "{colors.danger.700}",
        value: "#BC0130",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#BC0130",
          key: "{colors.danger.700}",
        },
        name: "ColorsDanger700",
        attributes: {
          category: "colors",
          type: "danger",
          item: "700",
        },
        path: ["colors", "danger", "700"],
      },
      800: {
        key: "{colors.danger.800}",
        value: "#7F0120",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#7F0120",
          key: "{colors.danger.800}",
        },
        name: "ColorsDanger800",
        attributes: {
          category: "colors",
          type: "danger",
          item: "800",
        },
        path: ["colors", "danger", "800"],
      },
      900: {
        key: "{colors.danger.900}",
        value: "#3D000F",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#3D000F",
          key: "{colors.danger.900}",
        },
        name: "ColorsDanger900",
        attributes: {
          category: "colors",
          type: "danger",
          item: "900",
        },
        path: ["colors", "danger", "900"],
      },
      950: {
        key: "{colors.danger.950}",
        value: "#1E0008",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#1E0008",
          key: "{colors.danger.950}",
        },
        name: "ColorsDanger950",
        attributes: {
          category: "colors",
          type: "danger",
          item: "950",
        },
        path: ["colors", "danger", "950"],
      },
    },
    success: {
      50: {
        key: "{colors.success.50}",
        value: "#F5FEEC",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#F5FEEC",
          key: "{colors.success.50}",
        },
        name: "ColorsSuccess50",
        attributes: {
          category: "colors",
          type: "success",
          item: "50",
        },
        path: ["colors", "success", "50"],
      },
      100: {
        key: "{colors.success.100}",
        value: "#EDFDDD",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#EDFDDD",
          key: "{colors.success.100}",
        },
        name: "ColorsSuccess100",
        attributes: {
          category: "colors",
          type: "success",
          item: "100",
        },
        path: ["colors", "success", "100"],
      },
      200: {
        key: "{colors.success.200}",
        value: "#D8FAB7",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#D8FAB7",
          key: "{colors.success.200}",
        },
        name: "ColorsSuccess200",
        attributes: {
          category: "colors",
          type: "success",
          item: "200",
        },
        path: ["colors", "success", "200"],
      },
      300: {
        key: "{colors.success.300}",
        value: "#C5F895",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#C5F895",
          key: "{colors.success.300}",
        },
        name: "ColorsSuccess300",
        attributes: {
          category: "colors",
          type: "success",
          item: "300",
        },
        path: ["colors", "success", "300"],
      },
      400: {
        key: "{colors.success.400}",
        value: "#B3F674",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#B3F674",
          key: "{colors.success.400}",
        },
        name: "ColorsSuccess400",
        attributes: {
          category: "colors",
          type: "success",
          item: "400",
        },
        path: ["colors", "success", "400"],
      },
      500: {
        key: "{colors.success.500}",
        value: "#A0F451",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#A0F451",
          key: "{colors.success.500}",
        },
        name: "ColorsSuccess500",
        attributes: {
          category: "colors",
          type: "success",
          item: "500",
        },
        path: ["colors", "success", "500"],
      },
      600: {
        key: "{colors.success.600}",
        value: "#7EF014",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#7EF014",
          key: "{colors.success.600}",
        },
        name: "ColorsSuccess600",
        attributes: {
          category: "colors",
          type: "success",
          item: "600",
        },
        path: ["colors", "success", "600"],
      },
      700: {
        key: "{colors.success.700}",
        value: "#5EB60C",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#5EB60C",
          key: "{colors.success.700}",
        },
        name: "ColorsSuccess700",
        attributes: {
          category: "colors",
          type: "success",
          item: "700",
        },
        path: ["colors", "success", "700"],
      },
      800: {
        key: "{colors.success.800}",
        value: "#3E7808",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#3E7808",
          key: "{colors.success.800}",
        },
        name: "ColorsSuccess800",
        attributes: {
          category: "colors",
          type: "success",
          item: "800",
        },
        path: ["colors", "success", "800"],
      },
      900: {
        key: "{colors.success.900}",
        value: "#203E04",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#203E04",
          key: "{colors.success.900}",
        },
        name: "ColorsSuccess900",
        attributes: {
          category: "colors",
          type: "success",
          item: "900",
        },
        path: ["colors", "success", "900"],
      },
      950: {
        key: "{colors.success.950}",
        value: "#0F1D02",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#0F1D02",
          key: "{colors.success.950}",
        },
        name: "ColorsSuccess950",
        attributes: {
          category: "colors",
          type: "success",
          item: "950",
        },
        path: ["colors", "success", "950"],
      },
    },
    grayscale: {
      50: {
        key: "{colors.grayscale.50}",
        value: "#F4F5F5",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#F4F5F5",
          key: "{colors.grayscale.50}",
        },
        name: "ColorsGrayscale50",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "50",
        },
        path: ["colors", "grayscale", "50"],
      },
      100: {
        key: "{colors.grayscale.100}",
        value: "#ECEEEE",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#ECEEEE",
          key: "{colors.grayscale.100}",
        },
        name: "ColorsGrayscale100",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "100",
        },
        path: ["colors", "grayscale", "100"],
      },
      200: {
        key: "{colors.grayscale.200}",
        value: "#D9DDDD",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#D9DDDD",
          key: "{colors.grayscale.200}",
        },
        name: "ColorsGrayscale200",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "200",
        },
        path: ["colors", "grayscale", "200"],
      },
      300: {
        key: "{colors.grayscale.300}",
        value: "#C6CDCC",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#C6CDCC",
          key: "{colors.grayscale.300}",
        },
        name: "ColorsGrayscale300",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "300",
        },
        path: ["colors", "grayscale", "300"],
      },
      400: {
        key: "{colors.grayscale.400}",
        value: "#B3BCBB",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#B3BCBB",
          key: "{colors.grayscale.400}",
        },
        name: "ColorsGrayscale400",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "400",
        },
        path: ["colors", "grayscale", "400"],
      },
      500: {
        key: "{colors.grayscale.500}",
        value: "#A0ABAA",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#A0ABAA",
          key: "{colors.grayscale.500}",
        },
        name: "ColorsGrayscale500",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "500",
        },
        path: ["colors", "grayscale", "500"],
      },
      600: {
        key: "{colors.grayscale.600}",
        value: "#7D8C8B",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#7D8C8B",
          key: "{colors.grayscale.600}",
        },
        name: "ColorsGrayscale600",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "600",
        },
        path: ["colors", "grayscale", "600"],
      },
      700: {
        key: "{colors.grayscale.700}",
        value: "#5D6A69",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#5D6A69",
          key: "{colors.grayscale.700}",
        },
        name: "ColorsGrayscale700",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "700",
        },
        path: ["colors", "grayscale", "700"],
      },
      800: {
        key: "{colors.grayscale.800}",
        value: "#3E4646",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#3E4646",
          key: "{colors.grayscale.800}",
        },
        name: "ColorsGrayscale800",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "800",
        },
        path: ["colors", "grayscale", "800"],
      },
      900: {
        key: "{colors.grayscale.900}",
        value: "#1F232",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#1F232",
          key: "{colors.grayscale.900}",
        },
        name: "ColorsGrayscale900",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "900",
        },
        path: ["colors", "grayscale", "900"],
      },
      950: {
        key: "{colors.grayscale.950}",
        value: "#0E1010",
        filePath: "src/tokens/colors.json",
        isSource: true,
        original: {
          value: "#0E1010",
          key: "{colors.grayscale.950}",
        },
        name: "ColorsGrayscale950",
        attributes: {
          category: "colors",
          type: "grayscale",
          item: "950",
        },
        path: ["colors", "grayscale", "950"],
      },
    },
  },
  opacities: {
    opaque: {
      key: "{opacities.opaque}",
      value: "1",
      filePath: "src/tokens/opacities.json",
      isSource: true,
      original: {
        value: "1",
        key: "{opacities.opaque}",
      },
      name: "OpacitiesOpaque",
      attributes: {
        category: "opacities",
        type: "opaque",
      },
      path: ["opacities", "opaque"],
    },
    semiOpaque: {
      key: "{opacities.semiOpaque}",
      value: "0.75",
      filePath: "src/tokens/opacities.json",
      isSource: true,
      original: {
        value: "0.75",
        key: "{opacities.semiOpaque}",
      },
      name: "OpacitiesSemiOpaque",
      attributes: {
        category: "opacities",
        type: "semiOpaque",
      },
      path: ["opacities", "semiOpaque"],
    },
    transparent: {
      key: "{opacities.transparent}",
      value: "0.5",
      filePath: "src/tokens/opacities.json",
      isSource: true,
      original: {
        value: "0.5",
        key: "{opacities.transparent}",
      },
      name: "OpacitiesTransparent",
      attributes: {
        category: "opacities",
        type: "transparent",
      },
      path: ["opacities", "transparent"],
    },
    lightTransparent: {
      key: "{opacities.lightTransparent}",
      value: "0.25",
      filePath: "src/tokens/opacities.json",
      isSource: true,
      original: {
        value: "0.25",
        key: "{opacities.lightTransparent}",
      },
      name: "OpacitiesLightTransparent",
      attributes: {
        category: "opacities",
        type: "lightTransparent",
      },
      path: ["opacities", "lightTransparent"],
    },
    veryTransparent: {
      key: "{opacities.veryTransparent}",
      value: "0.1",
      filePath: "src/tokens/opacities.json",
      isSource: true,
      original: {
        value: "0.1",
        key: "{opacities.veryTransparent}",
      },
      name: "OpacitiesVeryTransparent",
      attributes: {
        category: "opacities",
        type: "veryTransparent",
      },
      path: ["opacities", "veryTransparent"],
    },
  },
  radius: {
    tiny: {
      key: "{radius.tiny}",
      value: "2px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "2px",
        key: "{radius.tiny}",
      },
      name: "RadiusTiny",
      attributes: {
        category: "radius",
        type: "tiny",
      },
      path: ["radius", "tiny"],
    },
    "extra-small": {
      key: "{radius.extra-small}",
      value: "4px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "4px",
        key: "{radius.extra-small}",
      },
      name: "RadiusExtraSmall",
      attributes: {
        category: "radius",
        type: "extra-small",
      },
      path: ["radius", "extra-small"],
    },
    small: {
      key: "{radius.small}",
      value: "6px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "6px",
        key: "{radius.small}",
      },
      name: "RadiusSmall",
      attributes: {
        category: "radius",
        type: "small",
      },
      path: ["radius", "small"],
    },
    "medium-small": {
      key: "{radius.medium-small}",
      value: "8px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "8px",
        key: "{radius.medium-small}",
      },
      name: "RadiusMediumSmall",
      attributes: {
        category: "radius",
        type: "medium-small",
      },
      path: ["radius", "medium-small"],
    },
    medium: {
      key: "{radius.medium}",
      value: "12px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "12px",
        key: "{radius.medium}",
      },
      name: "RadiusMedium",
      attributes: {
        category: "radius",
        type: "medium",
      },
      path: ["radius", "medium"],
    },
    large: {
      key: "{radius.large}",
      value: "16px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "16px",
        key: "{radius.large}",
      },
      name: "RadiusLarge",
      attributes: {
        category: "radius",
        type: "large",
      },
      path: ["radius", "large"],
    },
    "extra-large": {
      key: "{radius.extra-large}",
      value: "20px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "20px",
        key: "{radius.extra-large}",
      },
      name: "RadiusExtraLarge",
      attributes: {
        category: "radius",
        type: "extra-large",
      },
      path: ["radius", "extra-large"],
    },
    "super-large": {
      key: "{radius.super-large}",
      value: "24px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "24px",
        key: "{radius.super-large}",
      },
      name: "RadiusSuperLarge",
      attributes: {
        category: "radius",
        type: "super-large",
      },
      path: ["radius", "super-large"],
    },
    huge: {
      key: "{radius.huge}",
      value: "32px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "32px",
        key: "{radius.huge}",
      },
      name: "RadiusHuge",
      attributes: {
        category: "radius",
        type: "huge",
      },
      path: ["radius", "huge"],
    },
    gigantic: {
      key: "{radius.gigantic}",
      value: "40px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "40px",
        key: "{radius.gigantic}",
      },
      name: "RadiusGigantic",
      attributes: {
        category: "radius",
        type: "gigantic",
      },
      path: ["radius", "gigantic"],
    },
    full: {
      key: "{radius.full}",
      value: "999px",
      filePath: "src/tokens/radius.json",
      isSource: true,
      original: {
        value: "999px",
        key: "{radius.full}",
      },
      name: "RadiusFull",
      attributes: {
        category: "radius",
        type: "full",
      },
      path: ["radius", "full"],
    },
  },
  shadows: {
    xs: {
      key: "{shadows.xs}",
      value: "0px 1px 2px rgba(0, 0, 0, 0.1)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0px 1px 2px rgba(0, 0, 0, 0.1)",
        key: "{shadows.xs}",
      },
      name: "ShadowsXs",
      attributes: {
        category: "shadows",
        type: "xs",
      },
      path: ["shadows", "xs"],
    },
    s: {
      key: "{shadows.s}",
      value: "0px 2px 4px rgba(0, 0, 0, 0.15)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0px 2px 4px rgba(0, 0, 0, 0.15)",
        key: "{shadows.s}",
      },
      name: "ShadowsS",
      attributes: {
        category: "shadows",
        type: "s",
      },
      path: ["shadows", "s"],
    },
    m: {
      key: "{shadows.m}",
      value: "0px 4px 6px rgba(0, 0, 0, 0.2)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0px 4px 6px rgba(0, 0, 0, 0.2)",
        key: "{shadows.m}",
      },
      name: "ShadowsM",
      attributes: {
        category: "shadows",
        type: "m",
      },
      path: ["shadows", "m"],
    },
    l: {
      key: "{shadows.l}",
      value: "0px 6px 12px rgba(0, 0, 0, 0.25)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0px 6px 12px rgba(0, 0, 0, 0.25)",
        key: "{shadows.l}",
      },
      name: "ShadowsL",
      attributes: {
        category: "shadows",
        type: "l",
      },
      path: ["shadows", "l"],
    },
    xl: {
      key: "{shadows.xl}",
      value: "0px 8px 16px rgba(0, 0, 0, 0.3)",
      filePath: "src/tokens/shadows.json",
      isSource: true,
      original: {
        value: "0px 8px 16px rgba(0, 0, 0, 0.3)",
        key: "{shadows.xl}",
      },
      name: "ShadowsXl",
      attributes: {
        category: "shadows",
        type: "xl",
      },
      path: ["shadows", "xl"],
    },
  },
  spacing: {
    4: {
      key: "{spacing.4}",
      value: "4px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "4px",
        key: "{spacing.4}",
      },
      name: "Spacing4",
      attributes: {
        category: "spacing",
        type: "4",
      },
      path: ["spacing", "4"],
    },
    8: {
      key: "{spacing.8}",
      value: "8px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "8px",
        key: "{spacing.8}",
      },
      name: "Spacing8",
      attributes: {
        category: "spacing",
        type: "8",
      },
      path: ["spacing", "8"],
    },
    12: {
      key: "{spacing.12}",
      value: "12px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "12px",
        key: "{spacing.12}",
      },
      name: "Spacing12",
      attributes: {
        category: "spacing",
        type: "12",
      },
      path: ["spacing", "12"],
    },
    16: {
      key: "{spacing.16}",
      value: "16px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "16px",
        key: "{spacing.16}",
      },
      name: "Spacing16",
      attributes: {
        category: "spacing",
        type: "16",
      },
      path: ["spacing", "16"],
    },
    20: {
      key: "{spacing.20}",
      value: "20px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "20px",
        key: "{spacing.20}",
      },
      name: "Spacing20",
      attributes: {
        category: "spacing",
        type: "20",
      },
      path: ["spacing", "20"],
    },
    24: {
      key: "{spacing.24}",
      value: "24px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "24px",
        key: "{spacing.24}",
      },
      name: "Spacing24",
      attributes: {
        category: "spacing",
        type: "24",
      },
      path: ["spacing", "24"],
    },
    28: {
      key: "{spacing.28}",
      value: "28px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "28px",
        key: "{spacing.28}",
      },
      name: "Spacing28",
      attributes: {
        category: "spacing",
        type: "28",
      },
      path: ["spacing", "28"],
    },
    32: {
      key: "{spacing.32}",
      value: "32px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "32px",
        key: "{spacing.32}",
      },
      name: "Spacing32",
      attributes: {
        category: "spacing",
        type: "32",
      },
      path: ["spacing", "32"],
    },
    36: {
      key: "{spacing.36}",
      value: "36px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "36px",
        key: "{spacing.36}",
      },
      name: "Spacing36",
      attributes: {
        category: "spacing",
        type: "36",
      },
      path: ["spacing", "36"],
    },
    40: {
      key: "{spacing.40}",
      value: "40px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "40px",
        key: "{spacing.40}",
      },
      name: "Spacing40",
      attributes: {
        category: "spacing",
        type: "40",
      },
      path: ["spacing", "40"],
    },
    44: {
      key: "{spacing.44}",
      value: "44px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "44px",
        key: "{spacing.44}",
      },
      name: "Spacing44",
      attributes: {
        category: "spacing",
        type: "44",
      },
      path: ["spacing", "44"],
    },
    48: {
      key: "{spacing.48}",
      value: "48px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "48px",
        key: "{spacing.48}",
      },
      name: "Spacing48",
      attributes: {
        category: "spacing",
        type: "48",
      },
      path: ["spacing", "48"],
    },
    52: {
      key: "{spacing.52}",
      value: "52px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "52px",
        key: "{spacing.52}",
      },
      name: "Spacing52",
      attributes: {
        category: "spacing",
        type: "52",
      },
      path: ["spacing", "52"],
    },
    56: {
      key: "{spacing.56}",
      value: "56px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "56px",
        key: "{spacing.56}",
      },
      name: "Spacing56",
      attributes: {
        category: "spacing",
        type: "56",
      },
      path: ["spacing", "56"],
    },
    60: {
      key: "{spacing.60}",
      value: "60px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "60px",
        key: "{spacing.60}",
      },
      name: "Spacing60",
      attributes: {
        category: "spacing",
        type: "60",
      },
      path: ["spacing", "60"],
    },
    64: {
      key: "{spacing.64}",
      value: "64px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "64px",
        key: "{spacing.64}",
      },
      name: "Spacing64",
      attributes: {
        category: "spacing",
        type: "64",
      },
      path: ["spacing", "64"],
    },
    68: {
      key: "{spacing.68}",
      value: "68px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "68px",
        key: "{spacing.68}",
      },
      name: "Spacing68",
      attributes: {
        category: "spacing",
        type: "68",
      },
      path: ["spacing", "68"],
    },
    72: {
      key: "{spacing.72}",
      value: "72px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "72px",
        key: "{spacing.72}",
      },
      name: "Spacing72",
      attributes: {
        category: "spacing",
        type: "72",
      },
      path: ["spacing", "72"],
    },
    76: {
      key: "{spacing.76}",
      value: "76px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "76px",
        key: "{spacing.76}",
      },
      name: "Spacing76",
      attributes: {
        category: "spacing",
        type: "76",
      },
      path: ["spacing", "76"],
    },
    80: {
      key: "{spacing.80}",
      value: "80px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "80px",
        key: "{spacing.80}",
      },
      name: "Spacing80",
      attributes: {
        category: "spacing",
        type: "80",
      },
      path: ["spacing", "80"],
    },
    84: {
      key: "{spacing.84}",
      value: "84px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "84px",
        key: "{spacing.84}",
      },
      name: "Spacing84",
      attributes: {
        category: "spacing",
        type: "84",
      },
      path: ["spacing", "84"],
    },
    88: {
      key: "{spacing.88}",
      value: "88px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "88px",
        key: "{spacing.88}",
      },
      name: "Spacing88",
      attributes: {
        category: "spacing",
        type: "88",
      },
      path: ["spacing", "88"],
    },
    92: {
      key: "{spacing.92}",
      value: "92px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "92px",
        key: "{spacing.92}",
      },
      name: "Spacing92",
      attributes: {
        category: "spacing",
        type: "92",
      },
      path: ["spacing", "92"],
    },
    96: {
      key: "{spacing.96}",
      value: "96px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "96px",
        key: "{spacing.96}",
      },
      name: "Spacing96",
      attributes: {
        category: "spacing",
        type: "96",
      },
      path: ["spacing", "96"],
    },
    100: {
      key: "{spacing.100}",
      value: "100px",
      filePath: "src/tokens/spacing.json",
      isSource: true,
      original: {
        value: "100px",
        key: "{spacing.100}",
      },
      name: "Spacing100",
      attributes: {
        category: "spacing",
        type: "100",
      },
      path: ["spacing", "100"],
    },
  },
};
